### ISSUE TITLE
Problem in inference code

### ISSUE THREAD

**Issue by tahaspc82442** [mainaksingha01/APPLeNet#12]
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    main(args)
  File "train.py", line 153, in main
    trainer.train()
  File "/raid/biplab/taha/Dassl.pytorch/dassl/engine/trainer.py", line 386, in train
    super().train(self.start_epoch, self.max_epoch)
  File "/raid/biplab/taha/Dassl.pytorch/dassl/engine/trainer.py", line 251, in train
    self.after_epoch()
  File "/raid/biplab/taha/APPLeNet/models/applenet.py", line 415, in after_epoch
    curr_result = self.test()
  File "/raid/biplab/taha/anaconda3/envs/dassl/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/raid/biplab/taha/APPLeNet/models/applenet.py", line 477, in test
    logits, ctx_shifted, label = self.model_inference(input, label)
TypeError: model_inference() takes 2 positional arguments but 3 were given

**Comment by tahaspc82442** [comment]
this is the model_inference function

**Comment by tahaspc82442** [comment]
def model_inference(self, input):
        return self.model(input)

**Comment by mainaksingha01** [comment]
The trainer file is given here https://github.com/mainaksingha01/APPLeNet/blob/master/dassl/engine/trainer.py

**Comment by tahaspc82442** [comment]
I think the issue is at line 477 of applenet.py, model_inference function takes only one argument input but two pos arguments are passed

**Comment by mainaksingha01** [comment]
The model_inference function in applenet.py is initiated from dassl trainer file. You have to replace it with the given modified trainer file. Please check the code instructions.

**Comment by tahaspc82442** [comment]
worked thanks :)
